#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\ADT\Console\ArtisanApplication;

require __DIR__ . '/vendor/autoload.php';

$application = new ArtisanApplication(__DIR__);

exit($application->run($argv));
