<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('accounting_accounts', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('parent_account_id')->nullable()->index(); $table->string('account_code',64); $table->string('account_name',255); $table->string('account_type',64); $table->json('metadata')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['company_id','account_code']); });
        Schema::create('accounting_fiscal_years', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('name',128); $table->date('start_date'); $table->date('end_date'); $table->boolean('is_closed')->default(false); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_periods', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('fiscal_year_id')->index(); $table->string('name',128); $table->date('start_date'); $table->date('end_date'); $table->boolean('is_open')->default(true); $table->timestamp('closed_at')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); $table->index(['company_id','is_open']); });
        Schema::create('accounting_voucher_types', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('code',64); $table->string('name',128); $table->string('series_pattern',128); $table->boolean('auto_approve')->default(false); $table->boolean('is_active')->default(true); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['company_id','code']); });
        Schema::create('accounting_documents', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('voucher_type_id')->nullable()->index(); $table->uuid('fiscal_year_id')->nullable()->index(); $table->uuid('period_id')->nullable()->index(); $table->string('source_module',64); $table->string('source_document_type',64); $table->string('source_document_id',64); $table->string('document_number',128)->nullable(); $table->date('document_date'); $table->date('posting_date')->nullable(); $table->string('currency',3)->default('USD'); $table->decimal('exchange_rate',18,8)->default(1); $table->string('status',32)->default('draft'); $table->text('description')->nullable(); $table->json('metadata')->nullable(); $table->uuid('approved_by')->nullable(); $table->timestamp('approved_at')->nullable(); $table->uuid('posted_by')->nullable(); $table->timestamp('posted_at')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); $table->index(['company_id','status']); });
        Schema::create('accounting_journals', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('document_id')->index(); $table->uuid('voucher_type_id')->nullable()->index(); $table->uuid('fiscal_year_id')->nullable()->index(); $table->uuid('period_id')->nullable()->index(); $table->string('journal_number',128); $table->date('posting_date'); $table->string('currency',3); $table->decimal('exchange_rate',18,8)->default(1); $table->decimal('debit_total',18,6)->default(0); $table->decimal('credit_total',18,6)->default(0); $table->string('status',32)->default('posted'); $table->uuid('posted_by')->nullable(); $table->timestamp('posted_at')->nullable(); $table->string('signature_hash',128)->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_journal_lines', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('journal_id')->index(); $table->uuid('account_id')->index(); $table->uuid('cost_center_id')->nullable()->index(); $table->uuid('profit_center_id')->nullable()->index(); $table->json('dimensions')->nullable(); $table->string('line_currency',3); $table->decimal('line_exchange_rate',18,8)->default(1); $table->decimal('debit_amount',18,6)->default(0); $table->decimal('credit_amount',18,6)->default(0); $table->decimal('functional_debit_amount',18,6)->default(0); $table->decimal('functional_credit_amount',18,6)->default(0); $table->string('description',255)->nullable(); $table->timestamps(); });
        Schema::create('accounting_ledger_balances', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('account_id')->index(); $table->uuid('period_id')->nullable()->index(); $table->string('currency',3); $table->decimal('opening_debit',18,6)->default(0); $table->decimal('opening_credit',18,6)->default(0); $table->decimal('period_debit',18,6)->default(0); $table->decimal('period_credit',18,6)->default(0); $table->decimal('closing_debit',18,6)->default(0); $table->decimal('closing_credit',18,6)->default(0); $table->timestamps(); $table->unique(['company_id','account_id','period_id','currency'],'acct_ledger_unique_scope'); });
        Schema::create('accounting_posting_log', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('idempotency_key',255)->unique(); $table->string('source_module',64); $table->string('source_document_type',64); $table->string('source_document_id',64); $table->uuid('document_id')->nullable()->index(); $table->uuid('journal_id')->nullable()->index(); $table->string('status',32); $table->text('error_message')->nullable(); $table->json('request_payload')->nullable(); $table->json('response_payload')->nullable(); $table->timestamp('processed_at')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_tax_profiles', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('code',64); $table->string('name',128); $table->decimal('rate',10,4); $table->string('region',32)->nullable(); $table->boolean('is_active')->default(true); $table->json('metadata')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_dimensions', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('dimension_type',32); $table->string('code',64); $table->string('name',128); $table->boolean('is_active')->default(true); $table->json('metadata')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_budgets', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->uuid('fiscal_year_id')->nullable()->index(); $table->uuid('account_id')->nullable()->index(); $table->string('version_name',64); $table->decimal('amount',18,6); $table->string('currency',3)->default('USD'); $table->boolean('hard_stop')->default(false); $table->json('metadata')->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('accounting_exchange_rates', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('organization_id')->nullable()->index(); $table->uuid('company_id')->index(); $table->uuid('branch_id')->nullable()->index(); $table->uuid('department_id')->nullable()->index(); $table->string('base_currency',3); $table->string('quote_currency',3); $table->decimal('rate',18,8); $table->date('rate_date'); $table->string('source',64)->nullable(); $table->uuid('created_by')->nullable(); $table->uuid('updated_by')->nullable(); $table->uuid('deleted_by')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['company_id','base_currency','quote_currency','rate_date'],'acct_fx_unique_scope'); });
    }
    public function down(): void {
        Schema::dropIfExists('accounting_exchange_rates'); Schema::dropIfExists('accounting_budgets'); Schema::dropIfExists('accounting_dimensions'); Schema::dropIfExists('accounting_tax_profiles'); Schema::dropIfExists('accounting_posting_log'); Schema::dropIfExists('accounting_ledger_balances'); Schema::dropIfExists('accounting_journal_lines'); Schema::dropIfExists('accounting_journals'); Schema::dropIfExists('accounting_documents'); Schema::dropIfExists('accounting_voucher_types'); Schema::dropIfExists('accounting_periods'); Schema::dropIfExists('accounting_fiscal_years'); Schema::dropIfExists('accounting_accounts');
    }
};

