<?php
declare(strict_types=1);
namespace Modules\Accounting\Application\Services;
use Modules\Accounting\Application\Support\AccountingTime;
use Modules\Accounting\Application\DTOs\PostingRequest;
use Modules\Accounting\Domain\Repositories\Contracts\JournalLineRepositoryInterface;
use Modules\Accounting\Domain\Repositories\Contracts\JournalRepositoryInterface;
final class JournalEngine { public function __construct(private readonly JournalRepositoryInterface $journals, private readonly JournalLineRepositoryInterface $lines) {} public function createPostedJournal(PostingRequest $request,string $documentId,string $number,array $lines): string { $dr='0';$cr='0'; foreach($lines as $line){$dr=MoneyMath::add($dr,(string)$line['debit']);$cr=MoneyMath::add($cr,(string)$line['credit']);} $j=$this->journals->create(['organization_id'=>$request->organizationId,'company_id'=>$request->companyId,'branch_id'=>$request->branchId,'department_id'=>$request->departmentId,'document_id'=>$documentId,'journal_number'=>$number,'posting_date'=>$request->postingDate,'currency'=>$request->currency,'exchange_rate'=>$request->exchangeRate,'debit_total'=>$dr,'credit_total'=>$cr,'status'=>'posted','posted_at'=>AccountingTime::now()]); foreach($lines as $line){$debit=(string)$line['debit'];$credit=(string)$line['credit'];$rate=(string)$request->exchangeRate;$this->lines->create(['organization_id'=>$request->organizationId,'company_id'=>$request->companyId,'branch_id'=>$request->branchId,'department_id'=>$request->departmentId,'journal_id'=>$j->id,'account_id'=>$line['account_id'],'cost_center_id'=>$line['cost_center_id']??null,'profit_center_id'=>$line['profit_center_id']??null,'dimensions'=>$line['dimensions']??[],'line_currency'=>$request->currency,'line_exchange_rate'=>$rate,'debit_amount'=>$debit,'credit_amount'=>$credit,'functional_debit_amount'=>MoneyMath::mul($debit,$rate),'functional_credit_amount'=>MoneyMath::mul($credit,$rate),'description'=>$line['description']??null]); } return (string)$j->id; } }

