<?php

declare(strict_types=1);

namespace App\ADT\MakeModule;

/**
 * Plans the full module blueprint in memory (simulation phase).
 */
final class ModuleBlueprintPlanner
{
    /**
     * @return list<BlueprintArtifact>
     */
    public function plan(string $moduleName): array
    {
        $artifacts = [];
        $providerClass = "Modules\\{$moduleName}\\Providers\\{$moduleName}ServiceProvider";
        $date = date('Y-m-d');
        $slug = strtolower($moduleName);

        $this->addDirectory($artifacts, '');
        $this->addFile($artifacts, 'module.json', $this->manifest($moduleName, $providerClass));
        $this->addFile($artifacts, 'README.md', $this->readme($moduleName));
        $this->addFile($artifacts, 'ARCHITECTURE.md', $this->architecture($moduleName));
        $this->addFile($artifacts, 'CHANGELOG.md', $this->changelog($moduleName, $date));
        $this->addFile($artifacts, 'ROADMAP.md', $this->roadmap($moduleName));
        $this->addFile($artifacts, 'TODO.md', $this->todo($moduleName));
        $this->addFile($artifacts, 'TESTING.md', $this->testing($moduleName));
        $this->addFile($artifacts, 'routes.php', $this->routes($moduleName));
        $this->addFile($artifacts, "Providers/{$moduleName}ServiceProvider.php", $this->provider($moduleName, $providerClass));

        $directories = [
            'Database/Migrations',
            'Database/Seeders',
            'Database/Factories',
            'Domain/Models',
            'Domain/Repositories/Contracts',
            'Domain/Events',
            'Domain/Enums',
            'Domain/ValueObjects',
            'Domain/Policies',
            'Application/Services',
            'Application/DTOs',
            'Application/Support',
            'Application/Commands',
            'Application/Listeners',
            'Infrastructure/Persistence',
            'Infrastructure/External',
            'Presentation/Views',
            'Presentation/Components',
            'Presentation/Layouts',
            'API/Controllers',
            'API/Resources',
            'API/Requests',
            'Tests/Unit',
            'Tests/Feature',
            'Tests/Integration',
            'DemoData',
        ];

        foreach ($directories as $directory) {
            $this->addDirectory($artifacts, $directory);
            $this->addFile($artifacts, $directory . '/.gitkeep', '');
        }

        $this->addFile(
            $artifacts,
            'Tests/Unit/ModuleBlueprintTest.php',
            $this->moduleSmokeTest($moduleName),
        );

        return $artifacts;
    }

    /**
     * @param list<BlueprintArtifact> $artifacts
     */
    private function addDirectory(array &$artifacts, string $relativePath): void
    {
        $artifacts[] = new BlueprintArtifact($relativePath, '', true);
    }

    /**
     * @param list<BlueprintArtifact> $artifacts
     */
    private function addFile(array &$artifacts, string $relativePath, string $content): void
    {
        $artifacts[] = new BlueprintArtifact($relativePath, $content, false);
    }

    private function manifest(string $moduleName, string $providerClass): string
    {
        $payload = [
            'name' => $moduleName,
            'type' => 'module',
            'version' => '1.0.0',
            'description' => "{$moduleName} module blueprint generated by AxiomOS ADT",
            'provider' => $providerClass,
            'enabled' => false,
            'priority' => 100,
            'minimumCoreVersion' => '1.0.0',
            'dependencies' => ['Core'],
            'permissions' => [],
            'events' => [],
            'routes' => [],
            'providers' => [$providerClass],
            'migrations' => [],
            'seeders' => [],
            'authors' => [
                ['name' => 'AxiomOS Team'],
            ],
            'ai' => new \stdClass(),
            'marketplace' => new \stdClass(),
            'upgrade' => new \stdClass(),
        ];

        return json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL;
    }

    private function readme(string $moduleName): string
    {
        return <<<MD
# {$moduleName} Module

## Overview
Blueprint module generated by AxiomOS ADT (`axiomos:make-module`).

## Status
- Version: 1.0.0
- State: Blueprint (not yet implemented)

## Structure
- `Domain/` business models and contracts
- `Application/` use cases and services
- `Infrastructure/` persistence and integrations
- `Presentation/` UI layer
- `API/` HTTP API layer
- `Database/` migrations, seeders, factories
- `Tests/` module test suites
- `DemoData/` non-production demo datasets

## Getting Started
1. Review `ARCHITECTURE.md` and `TODO.md`
2. Implement domain and application layers
3. Enable module in `module.json` when ready
4. Run module tests and quality gates

MD;
    }

    private function architecture(string $moduleName): string
    {
        return <<<MD
# {$moduleName} Architecture

## Layering
This module follows AxiomOS DDD + hexagonal architecture:

- **Domain**: entities, value objects, repository contracts, policies
- **Application**: services, DTOs, orchestration
- **Infrastructure**: persistence adapters and external integrations
- **Presentation/API**: delivery mechanisms only

## Dependencies
- Core module
- Platform services (`app/Platform`)

## Boundaries
- No persistence logic in Domain
- No business rules in Presentation/API
- Cross-module integration via events/contracts only

## ADT Governance
Generated under Rule 0 (simulation-first, developer approval required).

MD;
    }

    private function changelog(string $moduleName, string $date): string
    {
        return <<<MD
# Changelog

## [1.0.0] - {$date}
### Added
- Initial {$moduleName} module blueprint generated by ADT
- Standard directory structure and documentation bundle

MD;
    }

    private function roadmap(string $moduleName): string
    {
        return <<<MD
# {$moduleName} Roadmap

## Phase 1 — Foundation
- [ ] Domain model design
- [ ] Repository contracts
- [ ] Application services

## Phase 2 — Delivery
- [ ] API endpoints
- [ ] Presentation screens
- [ ] Policies and permissions

## Phase 3 — Quality
- [ ] Unit and feature tests
- [ ] Demo data
- [ ] Documentation completion

MD;
    }

    private function todo(string $moduleName): string
    {
        return <<<MD
# {$moduleName} TODO

- [ ] Define bounded context and aggregates
- [ ] Add migrations
- [ ] Implement repositories
- [ ] Implement application services
- [ ] Add API controllers and routes
- [ ] Add UI views
- [ ] Add tests and demo data
- [ ] Enable module in `module.json`

MD;
    }

    private function testing(string $moduleName): string
    {
        return <<<MD
# {$moduleName} Testing Guide

## Suites
- `Tests/Unit` for pure domain/application logic
- `Tests/Feature` for module HTTP and integration flows
- `Tests/Integration` for persistence and external adapters

## Commands
```bash
composer test:module
composer quality:gate
```

## Minimum Gate
- Module smoke test passes
- Architecture rules pass
- No Domain-layer Eloquent repositories

MD;
    }

    private function routes(string $moduleName): string
    {
        $slug = strtolower($moduleName);

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * {$moduleName} module routes.
 *
 * Register API and web routes here when implementation begins.
 */
return static function (): void {
    // Example:
    // Router::get('/{$slug}', [{$moduleName}WebController::class, 'index']);
};

PHP;
    }

    private function provider(string $moduleName, string $providerClass): string
    {
        $slug = $this->slug($moduleName);

        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$moduleName}\\Providers;

use App\Core\Container\Contracts\ContainerInterface;
use App\Core\Module\Support\ModuleInfo;
use App\Core\Module\Support\ModuleServiceProvider;

/**
 * Service provider for the {$moduleName} module.
 */
final class {$moduleName}ServiceProvider extends ModuleServiceProvider
{
    public function register(ContainerInterface \$container): void
    {
        \$container->instance('module.{$slug}', new ModuleInfo('{$moduleName}', '1.0.0'));
    }
}

PHP;
    }

    private function moduleSmokeTest(string $moduleName): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$moduleName}\\Tests\\Unit;

use PHPUnit\Framework\TestCase;

final class ModuleBlueprintTest extends TestCase
{
    public function test_module_blueprint_is_bootstrappable(): void
    {
        self::assertTrue(class_exists(\\Modules\\{$moduleName}\\Providers\\{$moduleName}ServiceProvider::class));
    }
}

PHP;
    }

    private function slug(string $moduleName): string
    {
        return strtolower($moduleName);
    }
}
